// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

/*
Package calculatorpb is a generated protocol buffer package.

It is generated from these files:
	calculator/calculatorpb/calculator.proto

It has these top-level messages:
	SumRequest
	SumResponse
	PrimeNumberDecompositionRequest
	PrimeNumberDecompositionResponse
	ComputeAverageRequest
	ComputeAverageResponse
	FindMaximumRequest
	FindMaximumResponse
*/
package calculatorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SumRequest struct {
	FirstNumber  int32 `protobuf:"varint,1,opt,name=first_number,json=firstNumber" json:"first_number,omitempty"`
	SecondNumber int32 `protobuf:"varint,2,opt,name=second_number,json=secondNumber" json:"second_number,omitempty"`
}

func (m *SumRequest) Reset()                    { *m = SumRequest{} }
func (m *SumRequest) String() string            { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()               {}
func (*SumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumResponse struct {
	SumResult int32 `protobuf:"varint,1,opt,name=sum_result,json=sumResult" json:"sum_result,omitempty"`
}

func (m *SumResponse) Reset()                    { *m = SumResponse{} }
func (m *SumResponse) String() string            { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()               {}
func (*SumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SumResponse) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

type PrimeNumberDecompositionRequest struct {
	Number int64 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *PrimeNumberDecompositionRequest) Reset()                    { *m = PrimeNumberDecompositionRequest{} }
func (m *PrimeNumberDecompositionRequest) String() string            { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionRequest) ProtoMessage()               {}
func (*PrimeNumberDecompositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PrimeNumberDecompositionRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberDecompositionResponse struct {
	PrimeFactor int64 `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor" json:"prime_factor,omitempty"`
}

func (m *PrimeNumberDecompositionResponse) Reset()         { *m = PrimeNumberDecompositionResponse{} }
func (m *PrimeNumberDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionResponse) ProtoMessage()    {}
func (*PrimeNumberDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

func (m *PrimeNumberDecompositionResponse) GetPrimeFactor() int64 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

type ComputeAverageRequest struct {
	Number int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *ComputeAverageRequest) Reset()                    { *m = ComputeAverageRequest{} }
func (m *ComputeAverageRequest) String() string            { return proto.CompactTextString(m) }
func (*ComputeAverageRequest) ProtoMessage()               {}
func (*ComputeAverageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ComputeAverageRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type ComputeAverageResponse struct {
	Average float64 `protobuf:"fixed64,1,opt,name=average" json:"average,omitempty"`
}

func (m *ComputeAverageResponse) Reset()                    { *m = ComputeAverageResponse{} }
func (m *ComputeAverageResponse) String() string            { return proto.CompactTextString(m) }
func (*ComputeAverageResponse) ProtoMessage()               {}
func (*ComputeAverageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ComputeAverageResponse) GetAverage() float64 {
	if m != nil {
		return m.Average
	}
	return 0
}

type FindMaximumRequest struct {
	Number int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *FindMaximumRequest) Reset()                    { *m = FindMaximumRequest{} }
func (m *FindMaximumRequest) String() string            { return proto.CompactTextString(m) }
func (*FindMaximumRequest) ProtoMessage()               {}
func (*FindMaximumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FindMaximumRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FindMaximumResponse struct {
	Maximun int32 `protobuf:"varint,1,opt,name=maximun" json:"maximun,omitempty"`
}

func (m *FindMaximumResponse) Reset()                    { *m = FindMaximumResponse{} }
func (m *FindMaximumResponse) String() string            { return proto.CompactTextString(m) }
func (*FindMaximumResponse) ProtoMessage()               {}
func (*FindMaximumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FindMaximumResponse) GetMaximun() int32 {
	if m != nil {
		return m.Maximun
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*PrimeNumberDecompositionRequest)(nil), "calculator.PrimeNumberDecompositionRequest")
	proto.RegisterType((*PrimeNumberDecompositionResponse)(nil), "calculator.PrimeNumberDecompositionResponse")
	proto.RegisterType((*ComputeAverageRequest)(nil), "calculator.ComputeAverageRequest")
	proto.RegisterType((*ComputeAverageResponse)(nil), "calculator.ComputeAverageResponse")
	proto.RegisterType((*FindMaximumRequest)(nil), "calculator.FindMaximumRequest")
	proto.RegisterType((*FindMaximumResponse)(nil), "calculator.FindMaximumResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CalculatorService service

type CalculatorServiceClient interface {
	// unary
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	// Server stream
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error)
	// Client stream
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error)
	// BiDi stream
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := grpc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CalculatorService_serviceDesc.Streams[0], c.cc, "/calculator.CalculatorService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeNumberDecompositionResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDecompositionClient) Recv() (*PrimeNumberDecompositionResponse, error) {
	m := new(PrimeNumberDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_ComputeAverageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CalculatorService_serviceDesc.Streams[1], c.cc, "/calculator.CalculatorService/ComputeAverage", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceComputeAverageClient{stream}
	return x, nil
}

type CalculatorService_ComputeAverageClient interface {
	Send(*ComputeAverageRequest) error
	CloseAndRecv() (*ComputeAverageResponse, error)
	grpc.ClientStream
}

type calculatorServiceComputeAverageClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceComputeAverageClient) Send(m *ComputeAverageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageClient) CloseAndRecv() (*ComputeAverageResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ComputeAverageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CalculatorService_serviceDesc.Streams[2], c.cc, "/calculator.CalculatorService/FindMaximum", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceFindMaximumClient{stream}
	return x, nil
}

type CalculatorService_FindMaximumClient interface {
	Send(*FindMaximumRequest) error
	Recv() (*FindMaximumResponse, error)
	grpc.ClientStream
}

type calculatorServiceFindMaximumClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceFindMaximumClient) Send(m *FindMaximumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumClient) Recv() (*FindMaximumResponse, error) {
	m := new(FindMaximumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CalculatorService service

type CalculatorServiceServer interface {
	// unary
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	// Server stream
	PrimeNumberDecomposition(*PrimeNumberDecompositionRequest, CalculatorService_PrimeNumberDecompositionServer) error
	// Client stream
	ComputeAverage(CalculatorService_ComputeAverageServer) error
	// BiDi stream
	FindMaximum(CalculatorService_FindMaximumServer) error
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDecomposition(m, &calculatorServicePrimeNumberDecompositionServer{stream})
}

type CalculatorService_PrimeNumberDecompositionServer interface {
	Send(*PrimeNumberDecompositionResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDecompositionServer) Send(m *PrimeNumberDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).ComputeAverage(&calculatorServiceComputeAverageServer{stream})
}

type CalculatorService_ComputeAverageServer interface {
	SendAndClose(*ComputeAverageResponse) error
	Recv() (*ComputeAverageRequest, error)
	grpc.ServerStream
}

type calculatorServiceComputeAverageServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceComputeAverageServer) SendAndClose(m *ComputeAverageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceComputeAverageServer) Recv() (*ComputeAverageRequest, error) {
	m := new(ComputeAverageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CalculatorService_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).FindMaximum(&calculatorServiceFindMaximumServer{stream})
}

type CalculatorService_FindMaximumServer interface {
	Send(*FindMaximumResponse) error
	Recv() (*FindMaximumRequest, error)
	grpc.ServerStream
}

type calculatorServiceFindMaximumServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceFindMaximumServer) Send(m *FindMaximumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumServer) Recv() (*FindMaximumRequest, error) {
	m := new(FindMaximumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _CalculatorService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _CalculatorService_ComputeAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "FindMaximum",
			Handler:       _CalculatorService_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}

func init() { proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcf, 0x4f, 0xe2, 0x40,
	0x14, 0xde, 0x42, 0x60, 0xb3, 0xaf, 0x5d, 0x92, 0x9d, 0xcd, 0xb2, 0xa4, 0xc9, 0x2e, 0x30, 0x7b,
	0x69, 0xb2, 0x04, 0x08, 0x5e, 0xf4, 0xa8, 0x28, 0x37, 0x8d, 0x29, 0x9e, 0xf4, 0x40, 0x4a, 0x19,
	0x4c, 0x93, 0x4e, 0xa7, 0xce, 0x0f, 0xa2, 0x7f, 0xba, 0x37, 0xe3, 0xb4, 0xa5, 0x83, 0x50, 0xf5,
	0xd6, 0xf7, 0xf5, 0xfb, 0x31, 0x79, 0xdf, 0x0c, 0x78, 0x61, 0x10, 0x87, 0x2a, 0x0e, 0x24, 0xe3,
	0xa3, 0xf2, 0x33, 0x5d, 0x1a, 0xc3, 0x30, 0xe5, 0x4c, 0x32, 0x04, 0x25, 0x82, 0x6f, 0x00, 0xe6,
	0x8a, 0xfa, 0xe4, 0x41, 0x11, 0x21, 0x51, 0x1f, 0x9c, 0x75, 0xc4, 0x85, 0x5c, 0x24, 0x8a, 0x2e,
	0x09, 0xef, 0x58, 0x3d, 0xcb, 0x6b, 0xf8, 0xb6, 0xc6, 0xae, 0x34, 0x84, 0xfe, 0xc1, 0x77, 0x41,
	0x42, 0x96, 0xac, 0x0a, 0x4e, 0x4d, 0x73, 0x9c, 0x0c, 0xcc, 0x48, 0x78, 0x00, 0xb6, 0x76, 0x15,
	0x29, 0x4b, 0x04, 0x41, 0x7f, 0x00, 0x84, 0xa2, 0x0b, 0x4e, 0x84, 0x8a, 0x65, 0x6e, 0xfa, 0x4d,
	0x68, 0x82, 0x8a, 0x25, 0x3e, 0x81, 0xee, 0x35, 0x8f, 0x28, 0xc9, 0xc4, 0xe7, 0x24, 0x64, 0x34,
	0x65, 0x22, 0x92, 0x11, 0x4b, 0x8a, 0x83, 0xb5, 0xa1, 0x69, 0x1c, 0xa9, 0xee, 0xe7, 0x13, 0xbe,
	0x80, 0x5e, 0xb5, 0x34, 0x4f, 0xef, 0x83, 0x93, 0xbe, 0x72, 0x16, 0xeb, 0x20, 0x94, 0xac, 0x70,
	0xb0, 0x35, 0x36, 0xd3, 0x10, 0x1e, 0xc1, 0xaf, 0x29, 0xa3, 0xa9, 0x92, 0xe4, 0x74, 0x43, 0x78,
	0x70, 0x4f, 0x0e, 0xe7, 0x36, 0xb6, 0xb9, 0x13, 0x68, 0xbf, 0x15, 0xe4, 0x69, 0x1d, 0xf8, 0x1a,
	0x64, 0x90, 0x96, 0x58, 0x7e, 0x31, 0xe2, 0x01, 0xa0, 0x59, 0x94, 0xac, 0x2e, 0x83, 0xc7, 0x88,
	0x96, 0x2b, 0xaf, 0x4a, 0x18, 0xc1, 0xcf, 0x1d, 0x76, 0x69, 0x4f, 0x35, 0x94, 0xe4, 0xfc, 0x62,
	0x9c, 0x3c, 0xd7, 0xe0, 0xc7, 0x74, 0x5b, 0xec, 0x9c, 0xf0, 0x4d, 0x14, 0x12, 0x74, 0x0c, 0xf5,
	0xb9, 0xa2, 0xa8, 0x3d, 0x34, 0x6e, 0x41, 0x59, 0xb8, 0xfb, 0x7b, 0x0f, 0xcf, 0x72, 0xf0, 0x17,
	0xf4, 0x04, 0x9d, 0xaa, 0xd5, 0xa2, 0xff, 0xa6, 0xec, 0x83, 0xee, 0xdc, 0xc1, 0xe7, 0xc8, 0x45,
	0xf0, 0xd8, 0x42, 0x77, 0xd0, 0xda, 0xdd, 0x2e, 0xea, 0x9b, 0x1e, 0x07, 0xab, 0x72, 0xf1, 0x7b,
	0x94, 0xc2, 0xdc, 0xb3, 0x90, 0x0f, 0xb6, 0xb1, 0x58, 0xf4, 0xd7, 0x94, 0xed, 0xf7, 0xe3, 0x76,
	0x2b, 0xff, 0x67, 0x9e, 0x9e, 0x35, 0xb6, 0xce, 0x5a, 0xb7, 0x8e, 0xf9, 0xe4, 0x96, 0x4d, 0xfd,
	0xd0, 0x8e, 0x5e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x19, 0x53, 0x9a, 0x94, 0x03, 0x00, 0x00,
}
