// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

/*
Package calculatorpb is a generated protocol buffer package.

It is generated from these files:
	calculator/calculatorpb/calculator.proto

It has these top-level messages:
	SumRequest
	SumResponse
	PrimeNumberDecompositionRequest
	PrimeNumberDecompositionResponse
*/
package calculatorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SumRequest struct {
	FirstNumber  int32 `protobuf:"varint,1,opt,name=first_number,json=firstNumber" json:"first_number,omitempty"`
	SecondNumber int32 `protobuf:"varint,2,opt,name=second_number,json=secondNumber" json:"second_number,omitempty"`
}

func (m *SumRequest) Reset()                    { *m = SumRequest{} }
func (m *SumRequest) String() string            { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()               {}
func (*SumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumResponse struct {
	SumResult int32 `protobuf:"varint,1,opt,name=sum_result,json=sumResult" json:"sum_result,omitempty"`
}

func (m *SumResponse) Reset()                    { *m = SumResponse{} }
func (m *SumResponse) String() string            { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()               {}
func (*SumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SumResponse) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

type PrimeNumberDecompositionRequest struct {
	Number int64 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *PrimeNumberDecompositionRequest) Reset()                    { *m = PrimeNumberDecompositionRequest{} }
func (m *PrimeNumberDecompositionRequest) String() string            { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionRequest) ProtoMessage()               {}
func (*PrimeNumberDecompositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PrimeNumberDecompositionRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberDecompositionResponse struct {
	PrimeFactor int64 `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor" json:"prime_factor,omitempty"`
}

func (m *PrimeNumberDecompositionResponse) Reset()         { *m = PrimeNumberDecompositionResponse{} }
func (m *PrimeNumberDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionResponse) ProtoMessage()    {}
func (*PrimeNumberDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

func (m *PrimeNumberDecompositionResponse) GetPrimeFactor() int64 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*PrimeNumberDecompositionRequest)(nil), "calculator.PrimeNumberDecompositionRequest")
	proto.RegisterType((*PrimeNumberDecompositionResponse)(nil), "calculator.PrimeNumberDecompositionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CalculatorService service

type CalculatorServiceClient interface {
	// unary
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	// Server stream
	PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := grpc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimeNumberDecompositionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CalculatorService_serviceDesc.Streams[0], c.cc, "/calculator.CalculatorService/PrimeNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeNumberDecompositionClient interface {
	Recv() (*PrimeNumberDecompositionResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeNumberDecompositionClient) Recv() (*PrimeNumberDecompositionResponse, error) {
	m := new(PrimeNumberDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CalculatorService service

type CalculatorServiceServer interface {
	// unary
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	// Server stream
	PrimeNumberDecomposition(*PrimeNumberDecompositionRequest, CalculatorService_PrimeNumberDecompositionServer) error
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeNumberDecomposition(m, &calculatorServicePrimeNumberDecompositionServer{stream})
}

type CalculatorService_PrimeNumberDecompositionServer interface {
	Send(*PrimeNumberDecompositionResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeNumberDecompositionServer) Send(m *PrimeNumberDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeNumberDecomposition",
			Handler:       _CalculatorService_PrimeNumberDecomposition_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}

func init() { proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4b, 0x4b, 0xc4, 0x30,
	0x10, 0x80, 0xad, 0x8b, 0x0b, 0x4e, 0xab, 0x60, 0x0e, 0xeb, 0xb2, 0x20, 0xee, 0xc6, 0xcb, 0x82,
	0xcb, 0x2a, 0x7a, 0xd1, 0xab, 0xaf, 0xa3, 0x48, 0xeb, 0xc9, 0x4b, 0x69, 0xe3, 0x2c, 0x04, 0x9a,
	0x26, 0xe6, 0x21, 0xf8, 0x0f, 0xfd, 0x59, 0x62, 0xda, 0xda, 0x80, 0x14, 0xbd, 0x65, 0x3e, 0xbe,
	0x79, 0x64, 0x06, 0x96, 0xac, 0xa8, 0x98, 0xab, 0x0a, 0x2b, 0xf5, 0x59, 0xff, 0x54, 0x65, 0x10,
	0xac, 0x95, 0x96, 0x56, 0x12, 0xe8, 0x09, 0x7d, 0x06, 0xc8, 0x9c, 0x48, 0xf1, 0xcd, 0xa1, 0xb1,
	0x64, 0x01, 0xc9, 0x86, 0x6b, 0x63, 0xf3, 0xda, 0x89, 0x12, 0xf5, 0x34, 0x9a, 0x47, 0xcb, 0x9d,
	0x34, 0xf6, 0xec, 0xd1, 0x23, 0x72, 0x02, 0x7b, 0x06, 0x99, 0xac, 0x5f, 0x3b, 0x67, 0xdb, 0x3b,
	0x49, 0x03, 0x1b, 0x89, 0xae, 0x20, 0xf6, 0x55, 0x8d, 0x92, 0xb5, 0x41, 0x72, 0x04, 0x60, 0x9c,
	0xc8, 0x35, 0x1a, 0x57, 0xd9, 0xb6, 0xe8, 0xae, 0xf1, 0x82, 0xab, 0x2c, 0xbd, 0x86, 0xe3, 0x27,
	0xcd, 0x05, 0x36, 0xc9, 0x77, 0xc8, 0xa4, 0x50, 0xd2, 0x70, 0xcb, 0x65, 0xdd, 0x0d, 0x36, 0x81,
	0x71, 0x30, 0xd2, 0x28, 0x6d, 0x23, 0x7a, 0x0f, 0xf3, 0xe1, 0xd4, 0xb6, 0xfb, 0x02, 0x12, 0xf5,
	0xed, 0xe4, 0x9b, 0x82, 0x59, 0xd9, 0x55, 0x88, 0x3d, 0x7b, 0xf0, 0xe8, 0xe2, 0x33, 0x82, 0x83,
	0xdb, 0x9f, 0xa5, 0x64, 0xa8, 0xdf, 0x39, 0x43, 0x72, 0x05, 0xa3, 0xcc, 0x09, 0x32, 0x59, 0x07,
	0x1b, 0xec, 0x97, 0x35, 0x3b, 0xfc, 0xc5, 0x9b, 0x86, 0x74, 0x8b, 0x7c, 0xc0, 0x74, 0x68, 0x2c,
	0x72, 0x1a, 0xa6, 0xfd, 0xf1, 0xef, 0xd9, 0xea, 0x7f, 0x72, 0xd7, 0xf8, 0x3c, 0xba, 0xd9, 0x7f,
	0x49, 0xc2, 0xeb, 0x97, 0x63, 0x7f, 0xf3, 0xcb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xed, 0xfe,
	0x94, 0x88, 0x1f, 0x02, 0x00, 0x00,
}
